run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - revive
    - gofmt

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 50
  max-issues: 0